server:
  port: 8088
  # database
spring:
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.80.221:1521:htjcoracle
    username: crxt2
    password: crxt2
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
    tomcat:
      initial-size: 5
  jpa:
    database: ORACLE
    servlet:
        multipart:
          max-file-size: 128MB
          max-request-size: 128MB
mybatis:
      mapper-locations: mybatis/mapper/*.xml
      configuration:
              default-statement-timeout: 10
              map-underscore-to-camel-case: true

